// Root build.gradle for Void Odyssey
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.20'
    }
}


task clean(type: Delete) {
    delete rootProject.buildDir
}
